version: '3.9'

services:
  database:
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - portfolio
    ports:
      - 5432:5432
  # app:
  #   build: .
  #   ports:
  #     - 6969:3000
  #   depends_on:
  #     - database
  #   networks:
  #     - portfolio
  #   env_file:
  #     - .env.docker

networks:
  portfolio: